name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Espressif IoT Development Framework (ESP-IDF)
        # You may pin to the exact commit or the version.
        # uses: espressif/esp-idf-ci-action@8cd22ae10042fadc37890e81e9988a9113e7b506
        uses: espressif/esp-idf-ci-action@v1.1.0
        with:
          # Relative path under $GITHUB_WORKSPACE to place the repository
          #path: # optional, default is 
          # Version of ESP-IDF docker image to use
          esp_idf_version: release-v5.5
          # ESP32 variant to build for
          target: esp32s3
          # Command to run inside the docker container (default: builds the project)
          command: >-
            mkdir -p /tmp/qdtech-managed-patches/78__esp-ml307
            /tmp/qdtech-managed-patches/78__esp-wifi-connect/include
            /tmp/qdtech-managed-patches/78__esp-opus-encoder &&
            cp managed_components/78__esp-ml307/esp_udp.cc
            /tmp/qdtech-managed-patches/78__esp-ml307/ &&
            cp managed_components/78__esp-wifi-connect/wifi_configuration_ap.cc
            managed_components/78__esp-wifi-connect/wifi_station.cc
            /tmp/qdtech-managed-patches/78__esp-wifi-connect/ &&
            cp managed_components/78__esp-wifi-connect/include/wifi_configuration_ap.h
            managed_components/78__esp-wifi-connect/include/wifi_station.h
            /tmp/qdtech-managed-patches/78__esp-wifi-connect/include/ &&
            cp managed_components/78__esp-opus-encoder/CMakeLists.txt
            /tmp/qdtech-managed-patches/78__esp-opus-encoder/ &&
            rm -rf managed_components/78__esp-ml307
            managed_components/78__esp-wifi-connect
            managed_components/78__esp-opus-encoder &&
            idf.py reconfigure &&
            cp /tmp/qdtech-managed-patches/78__esp-ml307/esp_udp.cc
            managed_components/78__esp-ml307/ &&
            cp /tmp/qdtech-managed-patches/78__esp-wifi-connect/wifi_configuration_ap.cc
            /tmp/qdtech-managed-patches/78__esp-wifi-connect/wifi_station.cc
            managed_components/78__esp-wifi-connect/ &&
            cp /tmp/qdtech-managed-patches/78__esp-wifi-connect/include/wifi_configuration_ap.h
            /tmp/qdtech-managed-patches/78__esp-wifi-connect/include/wifi_station.h
            managed_components/78__esp-wifi-connect/include/ &&
            cp /tmp/qdtech-managed-patches/78__esp-opus-encoder/CMakeLists.txt
            managed_components/78__esp-opus-encoder/ &&
            idf.py build
                
